services:
  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spotify-session-server
    ports:
      - "3000:3000"
    networks:
      - spotify-session-network
    depends_on:
      - database
    volumes:
      - ./backend/logs:/usr/src/app/logs
  
  nginx:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    networks:
      - spotify-session-network
    depends_on:
      - node-server
    volumes:
      - ./frontend/public/html:/var/www/spotify-session-app/assets/html
      - ./frontend/public/css:/var/www/spotify-session-app/assets/css
      - ./frontend/public/icons:/var/www/spotify-session-app/assets/icon
      - ./server/logs:/var/log/nginx

  database:
    image: postgres:17.2-alpine
    container_name: postgresql-container
    env_file:
    - ./database/.env
    ports:
      - "5432:5432"
    networks:
      - spotify-session-network
    restart: on-failure
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
      - ./database/logs:/var/log/postgresql

networks:
  spotify-session-network:
    driver: bridge
