services:
  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dominic86/mursica-fm-backend:1.1.2-alpha.1
    container_name: mursica-fm-backend
    env_file:
    - ./backend/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - mursica-fm-network
    depends_on:
      - database
    volumes:
      - ./backend/logs:/usr/src/app/logs
      - ./backend/.env:/usr/src/app/.env
      - ./backend/src:/usr/src/app/src
  
  nginx-proxy:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    image: dominic86/mursica-fm-proxy:1.1.2-alpha.1
    container_name: mursica-fm-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mursica-fm-network
    depends_on:
      - node-backend
    volumes:
      - ./frontend/public/html:/var/www/mursica-fm/assets/html
      - ./frontend/public/css:/var/www/mursica-fm/assets/css
      - ./frontend/public/icons:/var/www/mursica-fm/assets/icons
      - ./frontend/dist:/var/www/mursica-fm/assets/javascript
      - ./server/logs:/var/log/nginx

  database:
    image: postgres:17.2-alpine
    container_name: postgresql-container
    env_file:
    - ./database/.env
    ports:
      - "5432:5432"
    networks:
      - mursica-fm-network
    restart: on-failure
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/logs:/var/log/postgresql

networks:
  mursica-fm-network:
    driver: bridge
