services:
  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spotify-session-server
    ports:
      - "3000:3000"
    networks:
      - spotify-session-network

networks:
  spotify-session-network:
    driver: bridge
