services:
  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spotify-session-server
    ports:
      - "3000:3000"
    networks:
      - spotify-session-network
    volumes:
      - ./backend/logs:/usr/src/app/logs
  
  nginx:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    networks:
      - spotify-session-network
    depends_on:
      - node-server
    volumes:
      - ./frontend/public:/var/www/spotify-session-app/assets
      - ./server/logs:/var/log/nginx

networks:
  spotify-session-network:
    driver: bridge
